name: Validate Templates JSON

on:
  pull_request:
    paths:
      - 'templates.json'
  push:
      branches:
          - main

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate templates.json
        run: ./.github/workflows/script.sh
